WIP Avatar home page + library
vck3000/ProAvalon pull request #682
Opened 2024-05-15 08:19 UTC by kev306

2024-05-20 11:57 UTC, vck3000 commented on webpack.common.js
> +    avatarHome: './src/views/components/avatar/hydrate.tsx',
```suggestion
    avatarHome: './src/views/components/avatarHome/hydrate.tsx',
```

2024-05-20 11:59 UTC, vck3000 commented on src/views/components/avatar/index.tsx
> +  return <AvatarHomeUi />;
```suggestion
  return <AvatarHome />;
```

2024-05-20 12:01 UTC, vck3000 commented on src/views/components/avatar/avatarHome.tsx
> +    '../../avatars/base-res.svg',
```suggestion
    '/assets/avatars/base-res.svg',
```

2024-05-20 12:03 UTC, vck3000 commented on src/views/components/avatar/avatarHome.tsx
> +  const [avatarLibrary, setAvatarLibrary] = useState([]);
Can you type this guy?

2024-05-20 12:04 UTC, vck3000 commented on src/views/components/avatar/avatarHome.tsx
> +      const data = await response.json();
Let's type this data guy too

2024-05-20 12:06 UTC, vck3000 commented on src/views/components/avatar/avatarHome.tsx
> +      // TODO-kev: Remove the loading for this?
Option 1: static scaffold image
Option 2: loading gif

2024-05-20 12:18 UTC, vck3000 commented on src/views/components/avatar/avatarHome.tsx
> +    fetchUserAvatarInfo();
```suggestion
    void fetchUserAvatarInfo();
```

2024-05-20 12:24 UTC, vck3000 commented on src/views/components/avatar/avatarHome.tsx
> +          Swal.close();
Let's move this down next to the Swal.fire()

2024-05-20 12:31 UTC, vck3000 commented on src/routes/profile.tsx
>  import { PatreonAgent } from '../clients/patreon/patreonAgent';
Let's make a new folder called `profile`, keep the profile.ts here, and then have it import `profile/profile.ts` and `profile/avatar.ts`

2024-05-20 12:43 UTC, vck3000 commented on src/routes/profile.tsx
> +  async (req, res) => {
Let's try to type these guys.

2024-05-20 12:45 UTC, vck3000 commented on src/routes/profile.tsx
> +  '/:profileUsername/avatar/avatarinfo',
```suggestion
  '/:profileUsername/avatar/getAllAvatars',
```

2024-05-20 12:48 UTC, vck3000 commented on src/routes/profile.tsx
> +        user.usernameLower,
Let's change this to provide in the avatar library with avatar sets and "transform" them into links so the agent itself doesn't need to access the user model.

2024-05-20 12:53 UTC, vck3000 commented on src/clients/s3/S3Agent.ts
> +  private async updateUsersAvatarLibrary(usernameLower: string) {
Make this guy be called by getRewards each time.

2024-05-20 12:55 UTC, vck3000 commented on src/clients/s3/S3Agent.ts
> +  getLinkFromKey(key: string): string;
```suggestion
  transformKeyToLink(key: string): string;
```

2024-05-20 12:57 UTC, vck3000 commented on src/clients/s3/S3Agent.ts
>    deleteFile(link: string): any;
Update the return types!

2024-05-20 13:00 UTC, vck3000 commented on src/rewards/getRewards.ts
> +    return 10;
```suggestion
    return 5;
```

2024-05-20 13:02 UTC, vck3000 commented on src/clients/s3/S3Controller.ts
> +  public getLinkFromKey(key: string) {
```suggestion
  public transformKeyToLink(key: string) {
```

2024-05-21 06:35 UTC, kev306 commented on src/clients/s3/S3Agent.ts
> +interface ApprovedAvatarSet {
Initial thoughts from reviewing: The S3AvatarLinks interface is integrated in multiple files that will take time to merge. Considering whether to do it in this PR or a separate one

2024-05-22 04:08 UTC, kev306 commented on src/clients/s3/S3Agent.ts
> +interface ApprovedAvatarSet {
Change implemented within this pr on second thought

2024-05-23 04:17 UTC, vck3000 commented on src/routes/profile/profile.tsx
>  // @ts-nocheck
Let's rename this to index.tsx.

2024-05-23 04:18 UTC, vck3000 commented on src/clients/s3/S3Agent.ts
> +  moveFile(oldLink: string, newLink: string): void;
Promise if it's async

2024-05-23 04:25 UTC, vck3000 commented on src/rewards/getRewards.ts
> +  const user = await User.findOne({ usernameLower });
Can you replace this with the user get adapter.

2024-05-23 04:25 UTC, vck3000 commented on src/routes/profile/avatarRoutes.tsx
> +// @ts-nocheck
```suggestion

```

2024-05-23 04:33 UTC, vck3000 commented on src/routes/profile/avatarRoutes.tsx
> +// Change a users current avatar
```suggestion
// For a user to change their own current avatar
```

2024-05-23 04:34 UTC, vck3000 commented on src/routes/profile/avatarRoutes.tsx
> +// Get a users avatar library links
```suggestion
// Get a user's avatar library links
```

2024-05-23 04:35 UTC, vck3000 commented on src/routes/profile/avatarRoutes.tsx
> +router.get('/getallavatars', async (req, res) => {
```suggestion
router.get('/getalluseravatars', async (req, res) => {
```

2024-05-23 04:36 UTC, vck3000 commented on src/routes/profile/avatarRoutes.tsx
> +  const user = await User.findOne({
database adatper

2024-05-23 04:37 UTC, vck3000 commented on src/routes/profile/avatarRoutes.tsx
> +      user.avatarLibrary as number[],
Add this to IUser please to get rid of `as number[]`

2024-05-23 04:47 UTC, vck3000 commented on src/sockets/commands/mod/mpushavatartolibrary.ts
> -    const librarySize = await getAvatarLibrarySizeForUser(usernameLower);
Let's revert this

2024-05-23 04:50 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +      const response = await fetch('/profile/avatar/getallavatars');
Can you pull out these routes to a const at the top

2024-05-23 04:51 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +          src="https://giphy.com/embed/swhRkVYLJDrCE"
Replace with css

2024-05-23 04:52 UTC, vck3000 requested changes
-

2024-05-26 03:12 UTC, vck3000 commented on src/rewards/getRewards.ts
> +export async function getAvatarLibrarySizeForUser(
```
export async function getAvatarLibrarySizeForUser(
  usernameLower: string,
  patreonReward?: RewardType,
): Promise<number> {

  const patreonLibrarySize = async () => {
    if (!patreonReward) {
      patreonReward = await getPatreonRewardTierForUser(usernameLower);
    }

    if (patreonReward === constants.TIER1_BADGE) {
      return 2;
    } else if (patreonReward === constants.TIER2_BADGE) {
      return 3;
    } else if (patreonReward === constants.TIER3_BADGE) {
      return 5;
    } else if (patreonReward === constants.TIER4_BADGE) {
      return 10;
    } else {
      return 0;
    }
  };

 const modLibrarySize = () => {
   return isMod(usernameLower) ? 5 : 0;
  };

  return Math.max(await patreonLibrarySize(), modLibrarySize());
}
```

2024-05-26 03:27 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +type AvatarHomeRoutes = {
Let's make this an interface

2024-05-26 03:29 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +  edit: string;
```
const GetLinks = {
  getalluseravatars: (username: string) => `/profile/${username}/avatar/getalluseravatars`,
}
```

2024-05-27 09:18 UTC, vck3000 commented on src/databaseAdapters/user.ts
> +const userAdapter = new MongoUserAdapter();
Let's remove the export on L8

2024-05-27 09:20 UTC, vck3000 commented on src/gameplay/types.ts
> +  save: () => Promise<void>;
Can u add a comment above saying

```
// Mongoose methods
```

2024-05-27 09:22 UTC, vck3000 commented on src/rewards/getRewards.ts
> +      return 0;
```suggestion
      return TEMP_MIN_LIBRARY_SIZE; // 1;
```

2024-05-27 09:22 UTC, vck3000 commented on src/rewards/getRewards.ts
> +  const tempMinLibrarySize = 2;
Can we pull this const to the top.

2024-05-27 09:23 UTC, vck3000 commented on src/rewards/getRewards.ts
> +    tempMinLibrarySize,
```suggestion
    TEMP_MIN_LIBRARY_SIZE,
```

2024-05-27 09:32 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +    setUsername(extractedUsername);
Try to move the 2nd useEffect stuff here and use `extractedUsername`

2024-05-27 09:33 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +        data.currentResLink ? data.currentResLink : '/avatars/base-res.svg',
Let's move `/avatars/base-res.svg` to a const at the top or in a higher level file.

2024-05-27 09:33 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +        <div className="loader"></div>
Let's give this a more specific class name.

2024-05-27 09:34 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +      <a className="btn btn-info" href={GetLinks.customavatar(username)}>
```suggestion
      <a className="btn btn-info" href={getLinks.customavatar(username)}>
```

2024-05-27 09:37 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +      </h4>
Let's add the patreon stuff here in like 4 dot points or something super simple.

2024-05-27 09:37 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +          Until the DD/MM/YYYY, all users will be given a minimum avatar library
For a limited time until <date>, all users ...

2024-05-27 09:46 UTC, vck3000 commented on src/gameplay/types.ts
>    emailTokenExpiry?: Date;
Let's add that automated check to limit number of avatar requests if they've hit their max limit of library stuff.

2024-05-29 06:46 UTC, vck3000 commented on src/rewards/getRewards.ts
> +  // TODO-kev: Temporary minLibrarySize for feature launch. To be disabled DD/MM/YYYY
Remember to update before merging

2024-05-29 06:48 UTC, vck3000 commented on src/routes/profile/index.tsx
> +      errMsg: `You have exceeded your maximum number of avatars: ${librarySize}. Please support our Patreon to increase this limit.`,
```suggestion
      errMsg: `You have exceeded your maximum number of avatars: ${librarySize}.`,
```

2024-05-29 06:50 UTC, vck3000 commented on src/routes/profile/index.tsx
> +  // Check: Does not exceed avatar library size
```suggestion
  // Check: User has space in their user library
```

2024-05-29 06:51 UTC, vck3000 commented on src/routes/profile/index.tsx
> +    // Check: Both a singular res and spy avatar were submitted
Can you move this comment above the if

2024-05-29 06:52 UTC, vck3000 commented on src/views/components/avatarHome/avatarHome.tsx
> +    void fetchUserAvatarInfo();
Let's have this call below fetchUserAvatarInfo()

2024-05-29 06:58 UTC, vck3000 commented on src/routes/profile/index.tsx
> +});
rm

2024-05-29 06:58 UTC, vck3000 commented on src/sockets/commands/mod/mpushavatartolibrary.ts
> +    user.markModified('avatarLibrary');
This should be below L56

2024-05-29 06:59 UTC, vck3000 approved these changes

2024-06-01 14:40 UTC, merged